name: Deploy in beta
on: 
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh 2 commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: 22
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            echo "Hello world $CLONE_DIR"
            rm -rf /home/john/node-grp1
            git clone -b develop git@github.com:ZohraL/group1-api.git /home/john/node-grp1
            cd /home/john/node-grp1
            npm install
            npm run build
            mv /home/john/node-grp1/.env.beta /home/john/node-grp1/dist
            sed -i 's/my_port/${{ secrets.SSH_PORT }}/g' /home/john/node-grp1/dist/.env.beta
            shopt -s extglob
            rm -rf !(dist)
            cd dist
            npm install
            pm2 stop app-grp1
            pm2 start index.js --name "app-grp1"
    steps:
      - name: check http status code of production site
        uses: lakuapik/gh-actions-http-status@v1
        with:
          sites: 'http://localhost:8000/'
          expected: [200]

          