name: groupX-0
on:
  push:
    branches:
      - develop
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: no
          MYSQL_DATABASE: DICAPRIO_TEST
          MYSQL_PASSWORD: 1234
          MYSQL_USER: simplon
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: mmeisels/action-send-an-email-@v1
        env:
          SENDGRID_API_KEY: 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
        with:
          node-version: '15'
          emailToAddress: 'alexandrebobichon@gmail.com'
          emailFromAddress: 'laid.zohra@gmail.com'
          emailBody: 'email body text - can be html also'
      - name: Populate MySQL database
        run: bash pre-test.sh
        # $GITHUB_WORKSPACE
      - run: npm install
      - run: npm test